name: build design tokens

on:
  pull_request:
    paths:
      - "tokens.json"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: https://npm.pkg.github.com/

      - name: install node_modules
        run: yarn

      - name: build tokens
        run: yarn token

      - name: get pull request number
        run: echo "pr_number=$(${{ env.GITHUB_REF }} | awk -F'/' '{print $3}')" >> $GITHUB_OUTPUT
        id: pr_number

      - name: commit built tokens
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update design tokens (#${{ steps.pr_number.outputs.pr_number }})"
